server:
  port: 63792

# jwt configration
jwt:
  secret: 4b79626ed4ea188d7047df19deff58c2
  access_token_ttl: 900       # 15 minutes
  refresh_token_ttl: 86400    # 24 hours

# email configuration
email:
  host: smtp.qq.com
  port: 465
  username: pp
  password: 123


# database configuration
database:
  host: localhost
  port: 3306
  driver: mysql
  username: bobo
  password: bb123
  DBName: walk_user_db

# redis configuration
Redis:
  network: tcp
  addr: localhost:6379
  username: pp
  password: 123456
  db: 0
  poolSize: 10
  minIdleConns: 2
  maxIdleConns: 5
  maxRetries: 3 

# etcd configuration
etcd:
  endpoints:
    - "http://localhost:2379"
    - "http://localhost:22379"    
  dialTimeout: 5
  requestTimeout: 5
  # username:
  # password:
