servers:
  - name: user-service
    address: "127.0.0.1:50052"
    endpoints:
      - method: POST
        path: /api/auth/register
        grpc_service: userServer.UserService
        grpc_method: Register
        auth_required: false

      - method: POST
        path: /api/auth/login
        grpc_service: userServer.UserService
        grpc_method: Login
        auth_required: false

      - method: POST
        path: /api/auth/logout
        grpc_service: userServer.UserService
        grpc_method: Logout
        auth_required: true

      - method: GET
        path: /api/user/me
        grpc_service: userServer.UserService
        grpc_method: GetUser
        auth_required: true

      - method: PUT
        path: /api/user/me
        grpc_service: userServer.UserService
        grpc_method: UpdateUser
        auth_required: true

      - method: DELETE
        path: /api/user/me
        grpc_service: userServer.UserService
        grpc_method: DeleteUser
        auth_required: true

etcd:
  endpoints:
    - localhost:2379
  dial_timeout: 7