// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: apps/gateway/pb/grpc_gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用请求消息（用于协议转换和路由）
type Request struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Method            string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                                                             // HTTP 方法
	Path              string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                                                                 // 请求路径
	Headers           map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 请求头
	Body              []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // 请求体
	TargetServiceName string                 `protobuf:"bytes,5,opt,name=target_service_name,json=targetServiceName,proto3" json:"target_service_name,omitempty"`                            // 目标服务名称
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetTargetServiceName() string {
	if x != nil {
		return x.TargetServiceName
	}
	return ""
}

// 通用响应消息
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                  // HTTP 状态码
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应头
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // 响应体
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`                                                                             // 错误信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// 服务注册请求
type RegisterServiceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`          // 服务名称
	ServiceAddress string                 `protobuf:"bytes,2,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // 服务地址（如 "127.0.0.1:8080"）
	Endpoints      []string               `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`                                 // 服务端点列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceRequest) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *RegisterServiceRequest) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// 服务注册响应
type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 身份验证请求
type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                                               // 身份验证令牌
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 可选的请求头
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// 日志监控请求
type LogRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                                                             // HTTP 方法
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                                                                 // 请求路径
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 请求头
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // 请求体
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                                                         // 客户端 IP 地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequestMessage) Reset() {
	*x = LogRequestMessage{}
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequestMessage) ProtoMessage() {}

func (x *LogRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequestMessage.ProtoReflect.Descriptor instead.
func (*LogRequestMessage) Descriptor() ([]byte, []int) {
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *LogRequestMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogRequestMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogRequestMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *LogRequestMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LogRequestMessage) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// 错误处理请求
type HandleErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                                                     // 错误代码
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                             // 错误消息
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 错误上下文信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleErrorRequest) Reset() {
	*x = HandleErrorRequest{}
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleErrorRequest) ProtoMessage() {}

func (x *HandleErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_gateway_pb_grpc_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleErrorRequest.ProtoReflect.Descriptor instead.
func (*HandleErrorRequest) Descriptor() ([]byte, []int) {
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *HandleErrorRequest) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *HandleErrorRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HandleErrorRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_apps_gateway_pb_grpc_gateway_proto protoreflect.FileDescriptor

const file_apps_gateway_pb_grpc_gateway_proto_rawDesc = "" +
	"\n" +
	"\"apps/gateway/pb/grpc_gateway.proto\x12\agateway\"\xee\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x127\n" +
	"\aheaders\x18\x03 \x03(\v2\x1d.gateway.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12.\n" +
	"\x13target_service_name\x18\x05 \x01(\tR\x11targetServiceName\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x128\n" +
	"\aheaders\x18\x02 \x03(\v2\x1e.gateway.Response.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x16RegisterServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_address\x18\x02 \x01(\tR\x0eserviceAddress\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints\"M\n" +
	"\x17RegisterServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xac\x01\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12C\n" +
	"\aheaders\x18\x02 \x03(\v2).gateway.AuthenticateRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x01\n" +
	"\x11LogRequestMessage\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.gateway.LogRequestMessage.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\x12HandleErrorRequest\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12B\n" +
	"\acontext\x18\x03 \x03(\v2(.gateway.HandleErrorRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe3\x02\n" +
	"\x0eGatewayService\x126\n" +
	"\rHandleRequest\x12\x10.gateway.Request\x1a\x11.gateway.Response\"\x00\x12V\n" +
	"\x0fRegisterService\x12\x1f.gateway.RegisterServiceRequest\x1a .gateway.RegisterServiceResponse\"\x00\x12A\n" +
	"\fAuthenticate\x12\x1c.gateway.AuthenticateRequest\x1a\x11.gateway.Response\"\x00\x12=\n" +
	"\n" +
	"LogRequest\x12\x1a.gateway.LogRequestMessage\x1a\x11.gateway.Response\"\x00\x12?\n" +
	"\vHandleError\x12\x1b.gateway.HandleErrorRequest\x1a\x11.gateway.Response\"\x00B\x11Z\x0fapps/gateway/pbb\x06proto3"

var (
	file_apps_gateway_pb_grpc_gateway_proto_rawDescOnce sync.Once
	file_apps_gateway_pb_grpc_gateway_proto_rawDescData []byte
)

func file_apps_gateway_pb_grpc_gateway_proto_rawDescGZIP() []byte {
	file_apps_gateway_pb_grpc_gateway_proto_rawDescOnce.Do(func() {
		file_apps_gateway_pb_grpc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_gateway_pb_grpc_gateway_proto_rawDesc), len(file_apps_gateway_pb_grpc_gateway_proto_rawDesc)))
	})
	return file_apps_gateway_pb_grpc_gateway_proto_rawDescData
}

var file_apps_gateway_pb_grpc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_apps_gateway_pb_grpc_gateway_proto_goTypes = []any{
	(*Request)(nil),                 // 0: gateway.Request
	(*Response)(nil),                // 1: gateway.Response
	(*RegisterServiceRequest)(nil),  // 2: gateway.RegisterServiceRequest
	(*RegisterServiceResponse)(nil), // 3: gateway.RegisterServiceResponse
	(*AuthenticateRequest)(nil),     // 4: gateway.AuthenticateRequest
	(*LogRequestMessage)(nil),       // 5: gateway.LogRequestMessage
	(*HandleErrorRequest)(nil),      // 6: gateway.HandleErrorRequest
	nil,                             // 7: gateway.Request.HeadersEntry
	nil,                             // 8: gateway.Response.HeadersEntry
	nil,                             // 9: gateway.AuthenticateRequest.HeadersEntry
	nil,                             // 10: gateway.LogRequestMessage.HeadersEntry
	nil,                             // 11: gateway.HandleErrorRequest.ContextEntry
}
var file_apps_gateway_pb_grpc_gateway_proto_depIdxs = []int32{
	7,  // 0: gateway.Request.headers:type_name -> gateway.Request.HeadersEntry
	8,  // 1: gateway.Response.headers:type_name -> gateway.Response.HeadersEntry
	9,  // 2: gateway.AuthenticateRequest.headers:type_name -> gateway.AuthenticateRequest.HeadersEntry
	10, // 3: gateway.LogRequestMessage.headers:type_name -> gateway.LogRequestMessage.HeadersEntry
	11, // 4: gateway.HandleErrorRequest.context:type_name -> gateway.HandleErrorRequest.ContextEntry
	0,  // 5: gateway.GatewayService.HandleRequest:input_type -> gateway.Request
	2,  // 6: gateway.GatewayService.RegisterService:input_type -> gateway.RegisterServiceRequest
	4,  // 7: gateway.GatewayService.Authenticate:input_type -> gateway.AuthenticateRequest
	5,  // 8: gateway.GatewayService.LogRequest:input_type -> gateway.LogRequestMessage
	6,  // 9: gateway.GatewayService.HandleError:input_type -> gateway.HandleErrorRequest
	1,  // 10: gateway.GatewayService.HandleRequest:output_type -> gateway.Response
	3,  // 11: gateway.GatewayService.RegisterService:output_type -> gateway.RegisterServiceResponse
	1,  // 12: gateway.GatewayService.Authenticate:output_type -> gateway.Response
	1,  // 13: gateway.GatewayService.LogRequest:output_type -> gateway.Response
	1,  // 14: gateway.GatewayService.HandleError:output_type -> gateway.Response
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_apps_gateway_pb_grpc_gateway_proto_init() }
func file_apps_gateway_pb_grpc_gateway_proto_init() {
	if File_apps_gateway_pb_grpc_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_gateway_pb_grpc_gateway_proto_rawDesc), len(file_apps_gateway_pb_grpc_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_gateway_pb_grpc_gateway_proto_goTypes,
		DependencyIndexes: file_apps_gateway_pb_grpc_gateway_proto_depIdxs,
		MessageInfos:      file_apps_gateway_pb_grpc_gateway_proto_msgTypes,
	}.Build()
	File_apps_gateway_pb_grpc_gateway_proto = out.File
	file_apps_gateway_pb_grpc_gateway_proto_goTypes = nil
	file_apps_gateway_pb_grpc_gateway_proto_depIdxs = nil
}
